services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    # so it creates the uploads bucket on start
    entrypoint: ["/bin/sh", "-c", "mkdir -p /data/uploads && minio server /data --console-address ':9001'"]

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  cloudflared:
    image: cloudflare/cloudflared
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}