services:
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: minio server /data --console-address ':9001'
    volumes:
      - .data/minio:/data
  cloudflared:
    image: cloudflare/cloudflared:latest
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}