services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    # so it creates the uploads bucket on start
    entrypoint: ["/bin/sh", "-c", "mkdir -p /data/uploads && minio server /data --console-address ':9001'"]

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

  cloudflared:
    image: cloudflare/cloudflared
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}